# Copyright 2024 Google, LLC. This software is provided as-is,
# without warranty or representation for any use or purpose. Your
# use of it is subject to your agreement with Google.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import streamlit as st

##########################################################
# APPLICATION USER INTERFACE AND BACKBONE

st.title("Pathways Q&A evaluations v2.0")
st.subheader("Seattle Children Hospital")

logos_colums = st.columns(20)
logos_colums[0].image('./resources/sch-logo.gif', width=30)
logos_colums[1].image('./resources/gcp-logo.png', width=35)

st.error("""
This application is for internal testing only. Please, ignore any output
generated by this application for answering patient-related medical questions.
""")

st.info("Welcome to the 2nd version of the Pathway Q&A Application.")

st.markdown("""
This new version introduces **new functionalities**:

- You can **chat with Gemini** as you would do with an assistant.

- There are **two ways** to use the application:

    - You can start by discussing the **patient's condition,
    symptoms and history** or **SHC's protocol** to converge to a possible pathway.
    (for the moment, a short collection of pathways has been included in the application,
    but the entire collection will be soon available.)

    - Once the pathway has been chosen (or if you have already one), you can **ask questions**
    to Gemini about this **selected algorithm**.
""")

st.subheader("Important Information regarding Pathway Selection", divider="orange")

st.warning("""
    During the Pathway selection phase, Gemini will navigate through the **available pathways only**.

    If a pathway seems absent from the Gemini's conversation, check if it is available.

    If not, **consider an alternative
    source of information before making a decision** about the pathway to follow.
""")

with st.expander("Collection of Available Pathways"):
    st.selectbox("Available pathways", list(st.session_state['metadata'].keys())[:-2])
